#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_ThiTNTH")]
	public partial class TNTHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCauHoi(CauHoi instance);
    partial void UpdateCauHoi(CauHoi instance);
    partial void DeleteCauHoi(CauHoi instance);
    partial void InsertThongTinCaNhan(ThongTinCaNhan instance);
    partial void UpdateThongTinCaNhan(ThongTinCaNhan instance);
    partial void DeleteThongTinCaNhan(ThongTinCaNhan instance);
    partial void InsertDapAn(DapAn instance);
    partial void UpdateDapAn(DapAn instance);
    partial void DeleteDapAn(DapAn instance);
    partial void InsertDotThi(DotThi instance);
    partial void UpdateDotThi(DotThi instance);
    partial void DeleteDotThi(DotThi instance);
    partial void InsertKetQua(KetQua instance);
    partial void UpdateKetQua(KetQua instance);
    partial void DeleteKetQua(KetQua instance);
    partial void InsertKyThi(KyThi instance);
    partial void UpdateKyThi(KyThi instance);
    partial void DeleteKyThi(KyThi instance);
    partial void InsertPhanQuyen(PhanQuyen instance);
    partial void UpdatePhanQuyen(PhanQuyen instance);
    partial void DeletePhanQuyen(PhanQuyen instance);
    #endregion
		
		public TNTHDataContext() : 
				base(global::BLL_DAL.Properties.Settings.Default.QL_ThiTNTHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TNTHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TNTHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TNTHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TNTHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CauHoi> CauHois
		{
			get
			{
				return this.GetTable<CauHoi>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinCaNhan> ThongTinCaNhans
		{
			get
			{
				return this.GetTable<ThongTinCaNhan>();
			}
		}
		
		public System.Data.Linq.Table<DapAn> DapAns
		{
			get
			{
				return this.GetTable<DapAn>();
			}
		}
		
		public System.Data.Linq.Table<DotThi> DotThis
		{
			get
			{
				return this.GetTable<DotThi>();
			}
		}
		
		public System.Data.Linq.Table<KetQua> KetQuas
		{
			get
			{
				return this.GetTable<KetQua>();
			}
		}
		
		public System.Data.Linq.Table<KyThi> KyThis
		{
			get
			{
				return this.GetTable<KyThi>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyen> PhanQuyens
		{
			get
			{
				return this.GetTable<PhanQuyen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CauHoi")]
	public partial class CauHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCH;
		
		private string _HinhThucCH;
		
		private string _NoiDungCH;
		
		private string _HinhAnh;
		
		private int _DoKho;
		
		private EntitySet<DapAn> _DapAns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCHChanging(int value);
    partial void OnMaCHChanged();
    partial void OnHinhThucCHChanging(string value);
    partial void OnHinhThucCHChanged();
    partial void OnNoiDungCHChanging(string value);
    partial void OnNoiDungCHChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnDoKhoChanging(int value);
    partial void OnDoKhoChanged();
    #endregion
		
		public CauHoi()
		{
			this._DapAns = new EntitySet<DapAn>(new Action<DapAn>(this.attach_DapAns), new Action<DapAn>(this.detach_DapAns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaCH
		{
			get
			{
				return this._MaCH;
			}
			set
			{
				if ((this._MaCH != value))
				{
					this.OnMaCHChanging(value);
					this.SendPropertyChanging();
					this._MaCH = value;
					this.SendPropertyChanged("MaCH");
					this.OnMaCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucCH", DbType="NVarChar(50)")]
		public string HinhThucCH
		{
			get
			{
				return this._HinhThucCH;
			}
			set
			{
				if ((this._HinhThucCH != value))
				{
					this.OnHinhThucCHChanging(value);
					this.SendPropertyChanging();
					this._HinhThucCH = value;
					this.SendPropertyChanged("HinhThucCH");
					this.OnHinhThucCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungCH", DbType="NVarChar(500)")]
		public string NoiDungCH
		{
			get
			{
				return this._NoiDungCH;
			}
			set
			{
				if ((this._NoiDungCH != value))
				{
					this.OnNoiDungCHChanging(value);
					this.SendPropertyChanging();
					this._NoiDungCH = value;
					this.SendPropertyChanged("NoiDungCH");
					this.OnNoiDungCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoKho", DbType="Int NOT NULL")]
		public int DoKho
		{
			get
			{
				return this._DoKho;
			}
			set
			{
				if ((this._DoKho != value))
				{
					this.OnDoKhoChanging(value);
					this.SendPropertyChanging();
					this._DoKho = value;
					this.SendPropertyChanged("DoKho");
					this.OnDoKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DapAn", Storage="_DapAns", ThisKey="MaCH", OtherKey="MaCH")]
		public EntitySet<DapAn> DapAns
		{
			get
			{
				return this._DapAns;
			}
			set
			{
				this._DapAns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DapAns(DapAn entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = this;
		}
		
		private void detach_DapAns(DapAn entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinCaNhan")]
	public partial class ThongTinCaNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTS;
		
		private string _HoVaTenTS;
		
		private string _Email;
		
		private string _SDT;
		
		private string _CMND;
		
		private string _MatKhau;
		
		private string _MaLoaiTK;
		
		private string _MaKyThi;
		
		private System.DateTime _NgaySinh;
		
		private EntitySet<KetQua> _KetQuas;
		
		private EntityRef<KyThi> _KyThi;
		
		private EntityRef<PhanQuyen> _PhanQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTSChanging(int value);
    partial void OnMaTSChanged();
    partial void OnHoVaTenTSChanging(string value);
    partial void OnHoVaTenTSChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaLoaiTKChanging(string value);
    partial void OnMaLoaiTKChanged();
    partial void OnMaKyThiChanging(string value);
    partial void OnMaKyThiChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public ThongTinCaNhan()
		{
			this._KetQuas = new EntitySet<KetQua>(new Action<KetQua>(this.attach_KetQuas), new Action<KetQua>(this.detach_KetQuas));
			this._KyThi = default(EntityRef<KyThi>);
			this._PhanQuyen = default(EntityRef<PhanQuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTS
		{
			get
			{
				return this._MaTS;
			}
			set
			{
				if ((this._MaTS != value))
				{
					this.OnMaTSChanging(value);
					this.SendPropertyChanging();
					this._MaTS = value;
					this.SendPropertyChanged("MaTS");
					this.OnMaTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoVaTenTS", DbType="NVarChar(50)")]
		public string HoVaTenTS
		{
			get
			{
				return this._HoVaTenTS;
			}
			set
			{
				if ((this._HoVaTenTS != value))
				{
					this.OnHoVaTenTSChanging(value);
					this.SendPropertyChanging();
					this._HoVaTenTS = value;
					this.SendPropertyChanged("HoVaTenTS");
					this.OnHoVaTenTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(20)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(20)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiTK", DbType="NVarChar(50)")]
		public string MaLoaiTK
		{
			get
			{
				return this._MaLoaiTK;
			}
			set
			{
				if ((this._MaLoaiTK != value))
				{
					if (this._PhanQuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiTKChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiTK = value;
					this.SendPropertyChanged("MaLoaiTK");
					this.OnMaLoaiTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKyThi", DbType="VarChar(50)")]
		public string MaKyThi
		{
			get
			{
				return this._MaKyThi;
			}
			set
			{
				if ((this._MaKyThi != value))
				{
					if (this._KyThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKyThiChanging(value);
					this.SendPropertyChanging();
					this._MaKyThi = value;
					this.SendPropertyChanged("MaKyThi");
					this.OnMaKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinCaNhan_KetQua", Storage="_KetQuas", ThisKey="MaTS", OtherKey="MaTS")]
		public EntitySet<KetQua> KetQuas
		{
			get
			{
				return this._KetQuas;
			}
			set
			{
				this._KetQuas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KyThi_ThongTinCaNhan", Storage="_KyThi", ThisKey="MaKyThi", OtherKey="MaKT", IsForeignKey=true)]
		public KyThi KyThi
		{
			get
			{
				return this._KyThi.Entity;
			}
			set
			{
				KyThi previousValue = this._KyThi.Entity;
				if (((previousValue != value) 
							|| (this._KyThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KyThi.Entity = null;
						previousValue.ThongTinCaNhans.Remove(this);
					}
					this._KyThi.Entity = value;
					if ((value != null))
					{
						value.ThongTinCaNhans.Add(this);
						this._MaKyThi = value.MaKT;
					}
					else
					{
						this._MaKyThi = default(string);
					}
					this.SendPropertyChanged("KyThi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_ThongTinCaNhan", Storage="_PhanQuyen", ThisKey="MaLoaiTK", OtherKey="MaLoaiTK", IsForeignKey=true)]
		public PhanQuyen PhanQuyen
		{
			get
			{
				return this._PhanQuyen.Entity;
			}
			set
			{
				PhanQuyen previousValue = this._PhanQuyen.Entity;
				if (((previousValue != value) 
							|| (this._PhanQuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanQuyen.Entity = null;
						previousValue.ThongTinCaNhans.Remove(this);
					}
					this._PhanQuyen.Entity = value;
					if ((value != null))
					{
						value.ThongTinCaNhans.Add(this);
						this._MaLoaiTK = value.MaLoaiTK;
					}
					else
					{
						this._MaLoaiTK = default(string);
					}
					this.SendPropertyChanged("PhanQuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.ThongTinCaNhan = this;
		}
		
		private void detach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.ThongTinCaNhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DapAn")]
	public partial class DapAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDA;
		
		private System.Nullable<int> _MaCH;
		
		private System.Nullable<bool> _DungSai;
		
		private string _NoiDungDA;
		
		private EntityRef<CauHoi> _CauHoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDAChanging(int value);
    partial void OnMaDAChanged();
    partial void OnMaCHChanging(System.Nullable<int> value);
    partial void OnMaCHChanged();
    partial void OnDungSaiChanging(System.Nullable<bool> value);
    partial void OnDungSaiChanged();
    partial void OnNoiDungDAChanging(string value);
    partial void OnNoiDungDAChanged();
    #endregion
		
		public DapAn()
		{
			this._CauHoi = default(EntityRef<CauHoi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDA
		{
			get
			{
				return this._MaDA;
			}
			set
			{
				if ((this._MaDA != value))
				{
					this.OnMaDAChanging(value);
					this.SendPropertyChanging();
					this._MaDA = value;
					this.SendPropertyChanged("MaDA");
					this.OnMaDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCH", DbType="Int")]
		public System.Nullable<int> MaCH
		{
			get
			{
				return this._MaCH;
			}
			set
			{
				if ((this._MaCH != value))
				{
					if (this._CauHoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCHChanging(value);
					this.SendPropertyChanging();
					this._MaCH = value;
					this.SendPropertyChanged("MaCH");
					this.OnMaCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungSai", DbType="Bit")]
		public System.Nullable<bool> DungSai
		{
			get
			{
				return this._DungSai;
			}
			set
			{
				if ((this._DungSai != value))
				{
					this.OnDungSaiChanging(value);
					this.SendPropertyChanging();
					this._DungSai = value;
					this.SendPropertyChanged("DungSai");
					this.OnDungSaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungDA", DbType="NVarChar(500)")]
		public string NoiDungDA
		{
			get
			{
				return this._NoiDungDA;
			}
			set
			{
				if ((this._NoiDungDA != value))
				{
					this.OnNoiDungDAChanging(value);
					this.SendPropertyChanging();
					this._NoiDungDA = value;
					this.SendPropertyChanged("NoiDungDA");
					this.OnNoiDungDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DapAn", Storage="_CauHoi", ThisKey="MaCH", OtherKey="MaCH", IsForeignKey=true)]
		public CauHoi CauHoi
		{
			get
			{
				return this._CauHoi.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi.Entity = null;
						previousValue.DapAns.Remove(this);
					}
					this._CauHoi.Entity = value;
					if ((value != null))
					{
						value.DapAns.Add(this);
						this._MaCH = value.MaCH;
					}
					else
					{
						this._MaCH = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DotThi")]
	public partial class DotThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNgayThi;
		
		private string _NgayThi;
		
		private System.Nullable<int> _SoLuongDK;
		
		private EntitySet<KyThi> _KyThis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNgayThiChanging(string value);
    partial void OnMaNgayThiChanged();
    partial void OnNgayThiChanging(string value);
    partial void OnNgayThiChanged();
    partial void OnSoLuongDKChanging(System.Nullable<int> value);
    partial void OnSoLuongDKChanged();
    #endregion
		
		public DotThi()
		{
			this._KyThis = new EntitySet<KyThi>(new Action<KyThi>(this.attach_KyThis), new Action<KyThi>(this.detach_KyThis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNgayThi", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNgayThi
		{
			get
			{
				return this._MaNgayThi;
			}
			set
			{
				if ((this._MaNgayThi != value))
				{
					this.OnMaNgayThiChanging(value);
					this.SendPropertyChanging();
					this._MaNgayThi = value;
					this.SendPropertyChanged("MaNgayThi");
					this.OnMaNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThi", DbType="VarChar(30)")]
		public string NgayThi
		{
			get
			{
				return this._NgayThi;
			}
			set
			{
				if ((this._NgayThi != value))
				{
					this.OnNgayThiChanging(value);
					this.SendPropertyChanging();
					this._NgayThi = value;
					this.SendPropertyChanged("NgayThi");
					this.OnNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDK", DbType="Int")]
		public System.Nullable<int> SoLuongDK
		{
			get
			{
				return this._SoLuongDK;
			}
			set
			{
				if ((this._SoLuongDK != value))
				{
					this.OnSoLuongDKChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDK = value;
					this.SendPropertyChanged("SoLuongDK");
					this.OnSoLuongDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DotThi_KyThi", Storage="_KyThis", ThisKey="MaNgayThi", OtherKey="MaNgayThi")]
		public EntitySet<KyThi> KyThis
		{
			get
			{
				return this._KyThis;
			}
			set
			{
				this._KyThis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KyThis(KyThi entity)
		{
			this.SendPropertyChanging();
			entity.DotThi1 = this;
		}
		
		private void detach_KyThis(KyThi entity)
		{
			this.SendPropertyChanging();
			entity.DotThi1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQua")]
	public partial class KetQua : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTS;
		
		private string _MaKT;
		
		private System.Nullable<int> _Diem;
		
		private EntityRef<ThongTinCaNhan> _ThongTinCaNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTSChanging(int value);
    partial void OnMaTSChanged();
    partial void OnMaKTChanging(string value);
    partial void OnMaKTChanged();
    partial void OnDiemChanging(System.Nullable<int> value);
    partial void OnDiemChanged();
    #endregion
		
		public KetQua()
		{
			this._ThongTinCaNhan = default(EntityRef<ThongTinCaNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTS
		{
			get
			{
				return this._MaTS;
			}
			set
			{
				if ((this._MaTS != value))
				{
					if (this._ThongTinCaNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTSChanging(value);
					this.SendPropertyChanging();
					this._MaTS = value;
					this.SendPropertyChanged("MaTS");
					this.OnMaTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKT", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKT
		{
			get
			{
				return this._MaKT;
			}
			set
			{
				if ((this._MaKT != value))
				{
					this.OnMaKTChanging(value);
					this.SendPropertyChanging();
					this._MaKT = value;
					this.SendPropertyChanged("MaKT");
					this.OnMaKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diem", DbType="Int")]
		public System.Nullable<int> Diem
		{
			get
			{
				return this._Diem;
			}
			set
			{
				if ((this._Diem != value))
				{
					this.OnDiemChanging(value);
					this.SendPropertyChanging();
					this._Diem = value;
					this.SendPropertyChanged("Diem");
					this.OnDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinCaNhan_KetQua", Storage="_ThongTinCaNhan", ThisKey="MaTS", OtherKey="MaTS", IsForeignKey=true)]
		public ThongTinCaNhan ThongTinCaNhan
		{
			get
			{
				return this._ThongTinCaNhan.Entity;
			}
			set
			{
				ThongTinCaNhan previousValue = this._ThongTinCaNhan.Entity;
				if (((previousValue != value) 
							|| (this._ThongTinCaNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThongTinCaNhan.Entity = null;
						previousValue.KetQuas.Remove(this);
					}
					this._ThongTinCaNhan.Entity = value;
					if ((value != null))
					{
						value.KetQuas.Add(this);
						this._MaTS = value.MaTS;
					}
					else
					{
						this._MaTS = default(int);
					}
					this.SendPropertyChanged("ThongTinCaNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KyThi")]
	public partial class KyThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKT;
		
		private System.Nullable<int> _ThoiGianLamBai;
		
		private System.Nullable<int> _DotThi;
		
		private string _MaNgayThi;
		
		private EntitySet<ThongTinCaNhan> _ThongTinCaNhans;
		
		private EntityRef<DotThi> _DotThi1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKTChanging(string value);
    partial void OnMaKTChanged();
    partial void OnThoiGianLamBaiChanging(System.Nullable<int> value);
    partial void OnThoiGianLamBaiChanged();
    partial void OnDotThiChanging(System.Nullable<int> value);
    partial void OnDotThiChanged();
    partial void OnMaNgayThiChanging(string value);
    partial void OnMaNgayThiChanged();
    #endregion
		
		public KyThi()
		{
			this._ThongTinCaNhans = new EntitySet<ThongTinCaNhan>(new Action<ThongTinCaNhan>(this.attach_ThongTinCaNhans), new Action<ThongTinCaNhan>(this.detach_ThongTinCaNhans));
			this._DotThi1 = default(EntityRef<DotThi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKT", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKT
		{
			get
			{
				return this._MaKT;
			}
			set
			{
				if ((this._MaKT != value))
				{
					this.OnMaKTChanging(value);
					this.SendPropertyChanging();
					this._MaKT = value;
					this.SendPropertyChanged("MaKT");
					this.OnMaKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianLamBai", DbType="Int")]
		public System.Nullable<int> ThoiGianLamBai
		{
			get
			{
				return this._ThoiGianLamBai;
			}
			set
			{
				if ((this._ThoiGianLamBai != value))
				{
					this.OnThoiGianLamBaiChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianLamBai = value;
					this.SendPropertyChanged("ThoiGianLamBai");
					this.OnThoiGianLamBaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DotThi", DbType="Int")]
		public System.Nullable<int> DotThi
		{
			get
			{
				return this._DotThi;
			}
			set
			{
				if ((this._DotThi != value))
				{
					this.OnDotThiChanging(value);
					this.SendPropertyChanging();
					this._DotThi = value;
					this.SendPropertyChanged("DotThi");
					this.OnDotThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNgayThi", DbType="VarChar(50)")]
		public string MaNgayThi
		{
			get
			{
				return this._MaNgayThi;
			}
			set
			{
				if ((this._MaNgayThi != value))
				{
					if (this._DotThi1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNgayThiChanging(value);
					this.SendPropertyChanging();
					this._MaNgayThi = value;
					this.SendPropertyChanged("MaNgayThi");
					this.OnMaNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KyThi_ThongTinCaNhan", Storage="_ThongTinCaNhans", ThisKey="MaKT", OtherKey="MaKyThi")]
		public EntitySet<ThongTinCaNhan> ThongTinCaNhans
		{
			get
			{
				return this._ThongTinCaNhans;
			}
			set
			{
				this._ThongTinCaNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DotThi_KyThi", Storage="_DotThi1", ThisKey="MaNgayThi", OtherKey="MaNgayThi", IsForeignKey=true)]
		public DotThi DotThi1
		{
			get
			{
				return this._DotThi1.Entity;
			}
			set
			{
				DotThi previousValue = this._DotThi1.Entity;
				if (((previousValue != value) 
							|| (this._DotThi1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DotThi1.Entity = null;
						previousValue.KyThis.Remove(this);
					}
					this._DotThi1.Entity = value;
					if ((value != null))
					{
						value.KyThis.Add(this);
						this._MaNgayThi = value.MaNgayThi;
					}
					else
					{
						this._MaNgayThi = default(string);
					}
					this.SendPropertyChanged("DotThi1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThongTinCaNhans(ThongTinCaNhan entity)
		{
			this.SendPropertyChanging();
			entity.KyThi = this;
		}
		
		private void detach_ThongTinCaNhans(ThongTinCaNhan entity)
		{
			this.SendPropertyChanging();
			entity.KyThi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyen")]
	public partial class PhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiTK;
		
		private string _LoaiTK;
		
		private EntitySet<ThongTinCaNhan> _ThongTinCaNhans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiTKChanging(string value);
    partial void OnMaLoaiTKChanged();
    partial void OnLoaiTKChanging(string value);
    partial void OnLoaiTKChanged();
    #endregion
		
		public PhanQuyen()
		{
			this._ThongTinCaNhans = new EntitySet<ThongTinCaNhan>(new Action<ThongTinCaNhan>(this.attach_ThongTinCaNhans), new Action<ThongTinCaNhan>(this.detach_ThongTinCaNhans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiTK", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiTK
		{
			get
			{
				return this._MaLoaiTK;
			}
			set
			{
				if ((this._MaLoaiTK != value))
				{
					this.OnMaLoaiTKChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiTK = value;
					this.SendPropertyChanged("MaLoaiTK");
					this.OnMaLoaiTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTK", DbType="NVarChar(50)")]
		public string LoaiTK
		{
			get
			{
				return this._LoaiTK;
			}
			set
			{
				if ((this._LoaiTK != value))
				{
					this.OnLoaiTKChanging(value);
					this.SendPropertyChanging();
					this._LoaiTK = value;
					this.SendPropertyChanged("LoaiTK");
					this.OnLoaiTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_ThongTinCaNhan", Storage="_ThongTinCaNhans", ThisKey="MaLoaiTK", OtherKey="MaLoaiTK")]
		public EntitySet<ThongTinCaNhan> ThongTinCaNhans
		{
			get
			{
				return this._ThongTinCaNhans;
			}
			set
			{
				this._ThongTinCaNhans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThongTinCaNhans(ThongTinCaNhan entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = this;
		}
		
		private void detach_ThongTinCaNhans(ThongTinCaNhan entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = null;
		}
	}
}
#pragma warning restore 1591
